"""Add backtest_metrics table

Revision ID: 47e18b4f3661
Revises: 7b5bcb01486f
Create Date: 2026-09-12 21:23:44.621568

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47e18b4f3661"
down_revision: str | Sequence[str] | None = "7b5bcb01486f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_metrics",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("horizon", sa.String(), nullable=False),
        sa.Column("strategy_cumulative_return_pct", sa.Float(), nullable=True),
        sa.Column("baseline_cumulative_return_pct", sa.Float(), nullable=True),
        sa.Column("alpha_pct", sa.Float(), nullable=True),
        sa.Column("edge_check_status", sa.String(), nullable=True),
        sa.Column("calibration_status", sa.String(), nullable=True),
        sa.Column("calibration_ece", sa.Float(), nullable=True),
        sa.Column("is_live_worthy", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "horizon"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backtest_metrics")
    # ### end Alembic commands ###
