"""Add model_registry table

Revision ID: 6c0dbfc22edc
Revises: 47e18b4f3661
Create Date: 2026-09-12 23:26:48.614189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6c0dbfc22edc"
down_revision: Union[str, Sequence[str], None] = "47e18b4f3661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_registry",
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("horizon", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("git_commit", sa.String(), nullable=True),
        sa.Column("python_version", sa.String(), nullable=True),
        sa.Column("os_platform", sa.String(), nullable=True),
        sa.Column("sklearn_version", sa.String(), nullable=True),
        sa.Column("pandas_version", sa.String(), nullable=True),
        sa.Column("joblib_version", sa.String(), nullable=True),
        sa.Column("features_hash", sa.String(), nullable=True),
        sa.Column("artifact_path", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("model_version", "horizon"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_registry")
    # ### end Alembic commands ###
