"""Add backtest_metrics

Revision ID: 7b5bcb01486f
Revises: f42b93696645
Create Date: 2026-09-12 21:23:24.432985

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7b5bcb01486f"
down_revision: str | Sequence[str] | None = "f42b93696645"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
