"""Add symbol to model_registry

Revision ID: c095b1298a00
Revises: 6c0dbfc22edc
Create Date: 2026-09-12 23:29:22.405989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c095b1298a00"
down_revision: Union[str, Sequence[str], None] = "6c0dbfc22edc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_registry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("symbol", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_registry", schema=None) as batch_op:
        batch_op.drop_column("symbol")

    # ### end Alembic commands ###
