"""Initial schema

Revision ID: f42b93696645
Revises:
Create Date: 2026-09-12 21:17:24.008151

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f42b93696645"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.alter_column("event_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("source", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("event_type", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("scope", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("affected_tickers", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("sector", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("confidence_in_scope", existing_type=sa.REAL(), type_=sa.Float(), nullable=False)
        batch_op.alter_column("headline_or_label", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column("sentiment_score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
        batch_op.alter_column("magnitude_estimate", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f("ix_events_event_id"), ["event_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_events_id"), ["id"], unique=False)
        batch_op.drop_column("recorded_at")

    with op.batch_alter_table("health_status", schema=None) as batch_op:
        batch_op.alter_column("component", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column("status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("last_success_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("last_error", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("last_error_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("detail", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.create_index(batch_op.f("ix_health_status_component"), ["component"], unique=False)

    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.alter_column("symbol", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column("action", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
        batch_op.alter_column(
            "model_predicted_class", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column("raw_confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False)
        batch_op.alter_column(
            "risk_adjusted_confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False
        )
        batch_op.alter_column(
            "calibrated_confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column("agreement_fraction", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False)
        batch_op.alter_column("downside_summary", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("upside_summary", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("reasoning", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("global_risk_level", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column(
            "risk_toggle_enabled", existing_type=sa.INTEGER(), type_=sa.Boolean(), existing_nullable=True
        )
        batch_op.alter_column(
            "is_safe_to_trade_live", existing_type=sa.INTEGER(), type_=sa.Boolean(), existing_nullable=True
        )
        batch_op.alter_column("data_stale", existing_type=sa.INTEGER(), type_=sa.Boolean(), existing_nullable=True)
        batch_op.alter_column("suppressed", existing_type=sa.INTEGER(), type_=sa.Boolean(), existing_nullable=True)
        batch_op.alter_column("suppression_reasons", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column(
            "outcome_resolved",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column("outcome_correct", existing_type=sa.INTEGER(), type_=sa.Boolean(), existing_nullable=True)
        batch_op.alter_column(
            "outcome_actual_class", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column("resolved_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column(
            "horizon",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text("'INTRADAY'"),
        )
        batch_op.alter_column("narrative", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column("dca_ladder", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
        batch_op.alter_column(
            "model_version",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text("'UNKNOWN'"),
        )
        batch_op.alter_column(
            "feature_version",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text("'UNKNOWN'"),
        )
        batch_op.alter_column(
            "is_out_of_sample",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.create_index(batch_op.f("ix_predictions_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_predictions_symbol"), ["symbol"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_predictions_symbol"))
        batch_op.drop_index(batch_op.f("ix_predictions_id"))
        batch_op.alter_column(
            "is_out_of_sample",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            existing_nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "feature_version",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("'UNKNOWN'"),
        )
        batch_op.alter_column(
            "model_version",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("'UNKNOWN'"),
        )
        batch_op.alter_column("dca_ladder", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("narrative", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column(
            "horizon",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("'INTRADAY'"),
        )
        batch_op.alter_column("resolved_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column(
            "outcome_actual_class", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column("outcome_correct", existing_type=sa.Boolean(), type_=sa.INTEGER(), existing_nullable=True)
        batch_op.alter_column(
            "outcome_resolved",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            existing_nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column("suppression_reasons", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("suppressed", existing_type=sa.Boolean(), type_=sa.INTEGER(), existing_nullable=True)
        batch_op.alter_column("data_stale", existing_type=sa.Boolean(), type_=sa.INTEGER(), existing_nullable=True)
        batch_op.alter_column(
            "is_safe_to_trade_live", existing_type=sa.Boolean(), type_=sa.INTEGER(), existing_nullable=True
        )
        batch_op.alter_column(
            "risk_toggle_enabled", existing_type=sa.Boolean(), type_=sa.INTEGER(), existing_nullable=True
        )
        batch_op.alter_column("global_risk_level", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("reasoning", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("upside_summary", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("downside_summary", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("agreement_fraction", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False)
        batch_op.alter_column(
            "calibrated_confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "risk_adjusted_confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False
        )
        batch_op.alter_column("raw_confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False)
        batch_op.alter_column(
            "model_predicted_class", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column("action", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("symbol", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)

    with op.batch_alter_table("health_status", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_health_status_component"))
        batch_op.alter_column("detail", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("last_error_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("last_error", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("last_success_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("component", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recorded_at", sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_events_id"))
        batch_op.drop_index(batch_op.f("ix_events_event_id"))
        batch_op.alter_column("magnitude_estimate", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)
        batch_op.alter_column("sentiment_score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
        batch_op.alter_column("headline_or_label", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)
        batch_op.alter_column("confidence_in_scope", existing_type=sa.Float(), type_=sa.REAL(), nullable=True)
        batch_op.alter_column("sector", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column("affected_tickers", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("scope", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("event_type", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("source", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("event_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)

    # ### end Alembic commands ###
